name: Update RPM Repos
on:
  schedule:
  - cron: 0 0 * * *
  workflow_call:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  update_rpm_repo:
    if: github.repository_owner == 'ManageIQ'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Prepare options file
      run: |
        mkdir -p /tmp/options
        echo "---" > /tmp/options/options.yml
        echo "rpm_repository:" >> /tmp/options/options.yml
        echo "  s3_api:" >> /tmp/options/options.yml
        echo "    access_key: ${{ secrets.RPM_BUILD_S3_ACCESS_KEY }}" >> /tmp/options/options.yml
        echo "    secret_key: ${{ secrets.RPM_BUILD_S3_SECRET_KEY }}" >> /tmp/options/options.yml
    - name: Update RPM repo
      run: bin/run_update_rpm_repo
